### PR TITLE
CEP 2 - Plugin architecture for Conda

### PR DESCRIPTION
**Pull request by jezdez**
This is a quick draft for a CEP to add a plugin architecture to Conda which is pretty high-level. For specific implementations of the plugin API would need additional CEPs per use case (e.g. one for CLIs plugins, one for shell plugins etc).

### CODE REVIEW

**Comment by jezdez** [comment]
Aha, I was able to add multiple people as reviewers once the @conda/conda-core team was added to the repo.

**Review by xhochy — APPROVED** [review]

**Comment by jezdez** [comment]
Thank you for the review @xhochy!

**Review by chenghlee — APPROVED** [review]

**Comment by marcelotrevisani** [comment]
I would love to have several hooks like ``pytest`` does. something like pre-install hook, post-install, pre-link, post-link, pre fetch package, post fetch, pre-download, post-download, pre-extraction, post-extraction, pre-solver, solver, post-solver and so on

**Comment by jezdez** [comment]
> I would love to have several hooks like `pytest` does. something like pre-install hook, post-install, pre-link, post-link, pre fetch package, post fetch, pre-download, post-download, pre-extraction, post-extraction, pre-solver, solver, post-solver and so on

Good ideas! I added them to my list of use-cases which I'll use as part of future CEPs about specific use case implementations.

**Pull request merged**
