### PR TITLE
Mint CEP 19 and 20

### PR DESCRIPTION
**Pull request by jaimergp**
Follow up to #100 and #86

### CODE REVIEW

**Comment by jaimergp** [comment]
Added pre-commit.ci as a (bypassable) required check so we do not forget to mint CEPs before merging approved ones.

**Comment by beckermr** [comment]
Woops sorry!

**Comment by kenodegard** [comment]
And add to README?

**Comment by jaimergp** [comment]
Good point, Ken! Thanks!

**Pull request merged**
